{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9000/category',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: ''
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9000/category'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9000/category/ITEM_ID',
	requestHeader: {
		'content-type': 'application/json'
	},
	requestBody: {
		name: ''
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9000/category/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9000/category/ITEM_ID'
}