{
	des: 'Add',
	method: 'POST',
	url: 'http://localhost:9000/transaction',
	requestHeader: {
		'content-type': 'multipart/form-data'
	},
	requestBody: {
		'file:images': ''
	}
}

{
	des: 'Get list',
	method: 'GET',
	url: 'http://localhost:9000/transaction'
}

{
	des: 'Update',
	method: 'PUT',
	url: 'http://localhost:9000/transaction/ITEM_ID',
	requestHeader: {
		'content-type': 'multipart/form-data'
	},
	requestBody: {
		'file:images': ''
	}
}

{
	des: 'Get detail',
	method: 'GET',
	url: 'http://localhost:9000/transaction/ITEM_ID'
}

{
	des: 'Delete',
	method: 'DELETE',
	url: 'http://localhost:9000/transaction/ITEM_ID'
}